//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swd.PlayCollector.DataNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionItem
    {
        public long Id { get; set; }
        public Nullable<long> COL_LOCId { get; set; }
        public Nullable<long> COL_THEId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
